version: "3.9"
services:
  front :
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reactApp:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "cd next-app && npm install && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
